const ShopActionsTypes = {
    FETCH_COLLECTIONS: '[SHOP] FETCH COLLECTIONS',
    FETCH_COLLECTIONS_SUCCESS: '[SHOP] FETCH COLLECTIONS SUCCESS',
    FETCH_COLLECTIONS_FAILURE: '[SHOP] FETCH COLLECTIONS FAILURE',
    UPDATE_COLLECTIONS: '[SHOP] UPDATE COLLECTIONS'
};

export default ShopActionsTypes;